services:
  # 1. The Backend (Root Directory)
  - type: web
    name: finvault-backend
    runtime: docker
    repo: https://github.com/kristenstruening-ryan/finance-dashboard.git
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FINNHUB_KEY
        sync: false

  # 2. The Frontend (Client Directory)
  - type: web
    name: finvault-frontend
    runtime: docker
    repo: https://github.com/kristenstruening-ryan/finance-dashboard.git
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: finvault-backend
          property: url